---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: html_notebook
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
library(tidyverse)
devtools::load_all()
load('../data/d_final.rda')
```

## Construindo bd final

```{r}
d_cpopg <- readRDS('../data-raw/d_cpopg.rds')
d_cjpg <- readRDS('../data-raw/d_cjpg.rds')
```

### Somente processos digitais

```{r}
library(stringr)
digitais <- d_cpopg %>% 
  select(arq, infos) %>% 
  unnest(infos) %>% 
  filter(is.na(erro), key == 'digital', value == 'TRUE') %>% 
  select(arq) %>% 
  mutate(n_processo = tools::file_path_sans_ext(basename(arq)))
```

### Partes

```{r}
d_partes <- d_cpopg %>% 
  semi_join(digitais, 'arq') %>% 
  select(arq, partes) %>%
  unnest(partes) %>%
  select(-adv) %>% 
  separate(parte, c('parte', 'adv'), sep = '\n', 
           fill = 'right', extra = 'merge') %>% 
  mutate(adv = adv %>% 
           str_trim() %>% 
           str_replace_all('[[:space:]]+', ' ') %>% 
           str_replace('[^: ]+: ', '') %>% 
           str_split(' [^: ]+: '))


reu <- c('reqda', 'reqdo', 'reu', 'embargdo', 'exectdo', 're', 'imptdo',
         'exectda', 'embargda', 'impugdo', 'impugda')
autor <- c('reqte', 'embargte', 'autor', 'exeqte', 'imptte', 'autora',
           'impugte')
bancos <- c('banco', 'bank') %>% 
  str_c(collapse = '|') %>% 
  regex(ignore_case = TRUE)

so_bancos <- filter(d_partes, str_detect(parte, bancos))

d_partes_clean <- d_partes %>% 
  semi_join(so_bancos, 'arq') %>% 
  mutate(tipo_forma = if_else(forma %in% reu, 'reu', 
                              if_else(forma %in% autor, 'autor', 'outro'))) %>% 
  filter(tipo_forma != 'outro') %>% 
  unnest(adv) %>% 
  group_by(arq, tipo_forma) %>% 
  summarise(parte = paste(unique(parte), collapse = '\n'),
            adv = paste(unique(adv), collapse = '\n')) %>% 
  ungroup() %>% 
  unite(parte_adv, parte, adv, sep = '@@@') %>% 
  spread(tipo_forma, parte_adv) %>% 
  filter(!is.na(autor), !is.na(reu)) %>%
  separate(reu, c('reu', 'reu_adv'), sep = '@@@', fill = 'right') %>% 
  separate(autor, c('autor', 'autor_adv'), sep = '@@@', fill = 'right') %>% 
  mutate_at(vars(matches('^autor_|^reu_')), funs("n" = str_count(., '\n') + 1)) %>% 
  separate(reu, c('reu1', 'reu2', 'reu3', 'reu_outros'), 
           sep = '\n', extra = 'merge', fill = 'right') %>% 
  separate(autor, c('autor1', 'autor2', 'autor3', 'autor_outros'), 
           sep = '\n', extra = 'merge', fill = 'right') %>% 
  separate(reu_adv, c('adv_reu1', 'adv_reu2', 'adv_reu3', 'adv_reu_outros'), 
           sep = '\n', extra = 'merge', fill = 'right') %>% 
  separate(autor_adv, c('adv_autor1', 'adv_autor2', 'adv_autor3', 'adv_autor_outros'), 
           sep = '\n', extra = 'merge', fill = 'right') %>% 
  mutate_at(vars(starts_with('adv_')), funs(if_else(. == 'NA', NA_character_, .)))
```

```{r}
d_partes_clean <- d_partes %>% 
  semi_join(so_bancos, 'arq') %>% 
  mutate(tipo_forma = if_else(forma %in% reu, 'reu', 
                              if_else(forma %in% autor, 'autor', 'outro'))) %>% 
  filter(tipo_forma != 'outro') %>% 
  unnest(adv) %>% 
  group_by(arq, tipo_forma) %>% 
  summarise(parte = paste(unique(parte), collapse = '\n'),
            adv = paste(unique(adv), collapse = '\n')) %>% 
  ungroup() %>% 
  unite(parte_adv, parte, adv, sep = '@@@') %>% 
  spread(tipo_forma, parte_adv) %>% 
  filter(!is.na(autor), !is.na(reu)) %>%
  separate(reu, c('reu', 'reu_adv'), sep = '@@@', fill = 'right') %>% 
  separate(autor, c('autor', 'autor_adv'), sep = '@@@', fill = 'right') %>% 
  mutate_at(vars(matches('^autor_|^reu_')), funs("n" = str_count(., '\n') + 1)) %>% 
  filter(str_detect(reu, bancos)) %>% 
  group_by(arq) %>% 
  mutate(reu = reu %>% 
           str_split('\n', simplify = TRUE) %>% 
           str_subset(bancos) %>% 
           str_c(collapse = '\n')) %>% 
  ungroup() %>% 
  separate(reu, c('reu1', 'reu2', 'reu3', 'reu_outros'), 
           sep = '\n', extra = 'merge', fill = 'right') %>% 
  separate(autor, c('autor1', 'autor2', 'autor3', 'autor_outros'), 
           sep = '\n', extra = 'merge', fill = 'right') %>% 
  separate(reu_adv, c('adv_reu1', 'adv_reu2', 'adv_reu3', 'adv_reu_outros'), 
           sep = '\n', extra = 'merge', fill = 'right') %>% 
  separate(autor_adv, c('adv_autor1', 'adv_autor2', 'adv_autor3', 'adv_autor_outros'), 
           sep = '\n', extra = 'merge', fill = 'right') %>% 
  mutate_at(vars(starts_with('adv_')), funs(if_else(. == 'NA', NA_character_, .)))
```



### Resultados

```{r}
d_cjpg_clean <- d_cjpg %>% 
  mutate(n_processo = str_replace_all(n_processo, '[^0-9]', '')) %>% 
  semi_join(digitais, 'n_processo') %>% 
  arrange(desc(dt_sentenca)) %>% 
  distinct(n_processo, .keep_all = TRUE) %>% 
  select(n_processo, classe, assunto, magistrado, vara, dt_sentenca, txt)

d_cjpg %>% 
  mutate(n_processo = str_replace_all(n_processo, '[^0-9]', '')) %>% 
  semi_join(digitais, 'n_processo') %>% 
  arrange(desc(dt_sentenca)) %>% 
  janitor::get_dupes(n_processo) %>% 
  View

```




-------------------------------------------------------------------------------


```{r}
d_final
```

```{r}
d_final %>% glimpse()
```

```{r}
library(stringr)
d_reg <- d_final %>% 
  mutate(reu = reu %>% 
           toupper %>% 
           abjutils::rm_accent() %>% 
           str_replace_all(' S[/.]?A[.]?$|[^A-Z ]', '') %>% 
           str_replace_all('[[:space:]]+', ' ') %>% 
           str_trim()) %>% 
  transmute(n_processo = n_processo,
            digital = as.numeric(digital),
            data_distribuicao = as.numeric(data_distribuicao),
            valor = log10(valor_sm + 1e-4),
            magistrado = forcats::fct_lump(magistrado, prop = .005),
            vara = forcats::fct_lump(paste(foro, vara), prop = .005),
            comarca = forcats::fct_lump(comarca, prop = .01),
            reu = forcats::fct_lump(reu, prop = .01),
            y = as.factor(if_else(result %in% c('PROCEDENTE', 'PARCIALMENTE'), 1L, 0L)))
```

```{r}
d_reg %>% 
  summarise_if(is.factor, funs(nlevels)) %>% 
  gather
```

```{r}
library(modelr)
library(caret)
set.seed(474747)
d_tot <- d_reg %>% resample_partition(c(train = .8, test = .2))
d_train <- d_reg %>% slice(d_tot$train$idx) %>% select(-n_processo)
d_test <- d_reg %>% slice(d_tot$test$idx) %>% select(-n_processo)

# X <- model.matrix(y~., data = d_train)
obj_control <- trainControl(method = 'none', number = 1, returnResamp = 'none')
m <- train(y~., data = d_train, method = 'rf', 
           trControl = obj_control,
           tuneGrid = data.frame(mtry = 45))

m <- train(y~., data = d_train, method = 'glmnet')

d_test %>% 
  add_predictions(m) %>% 
  with(sum(pred == y) / length(y))
```

## Predição de resultados de processos

É possível predizer resultados de processos?

